name: Spotless check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests and spotless:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: maven
    - name: run spotless check
      run: mvn spotless:check
    - name: run unit tests
      run: mvn test
